In [10]:
import pickle
import numpy as np
import pandas as pd

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix
)

RANDOM_SEED = 559

with open("../data/preprocessed_data.pkl", "rb") as f:
    preprocessed_data = pickle.load(f)

X_train = preprocessed_data["X_train"]
X_val = preprocessed_data["X_val"]
X_test = preprocessed_data["X_test"]
y_train = preprocessed_data["y_train"]
y_val = preprocessed_data["y_val"]
y_test = preprocessed_data["y_test"]

print(X_train.shape)
print(X_val.shape)
print(X_test.shape)

print("y_train unique:", np.unique(y_train))
print("y_val unique:", np.unique(y_val))
print("y_test unique:", np.unique(y_test))

(1096, 100)
(235, 100)
(236, 100)
y_train unique: [-1  1]
y_val unique: [-1  1]
y_test unique: [-1  1]


In [11]:
rf_baseline = RandomForestClassifier(
    n_estimators=200,
    random_state=RANDOM_SEED,
    n_jobs=-1
)

rf_baseline.fit(X_train, y_train)
y_val_pred = rf_baseline.predict(X_val)

print("Validation Accuracy:", accuracy_score(y_val, y_val_pred))
print("Validation Precision:", precision_score(y_val, y_val_pred, pos_label=1, zero_division=0))
print("Validation Recall:", recall_score(y_val, y_val_pred, pos_label=1, zero_division=0))
print("Validation F1-score:", f1_score(y_val, y_val_pred, pos_label=1, zero_division=0))
print("Confusion Matrix:\n", confusion_matrix(y_val, y_val_pred))

Validation Accuracy: 0.9319148936170213
Validation Precision: 0.0
Validation Recall: 0.0
Validation F1-score: 0.0
Confusion Matrix:
 [[219   1]
 [ 15   0]]


In [12]:
rf_weighted = RandomForestClassifier(
    n_estimators=200,
    class_weight="balanced",
    random_state=RANDOM_SEED,
    n_jobs=-1
)

rf_weighted.fit(X_train, y_train)
y_val_pred = rf_weighted.predict(X_val)

print("Validation Accuracy:", accuracy_score(y_val, y_val_pred))
print("Validation Precision:", precision_score(y_val, y_val_pred, pos_label=1, zero_division=0))
print("Validation Recall:", recall_score(y_val, y_val_pred, pos_label=1, zero_division=0))
print("Validation F1-score:", f1_score(y_val, y_val_pred, pos_label=1, zero_division=0))
print("Confusion Matrix:\n", confusion_matrix(y_val, y_val_pred))

Validation Accuracy: 0.9361702127659575
Validation Precision: 0.0
Validation Recall: 0.0
Validation F1-score: 0.0
Confusion Matrix:
 [[220   0]
 [ 15   0]]


In [13]:
for w in [3, 5, 10, 15]:
    rf_model = RandomForestClassifier(
        n_estimators=200,
        class_weight={-1: 1, 1: w},
        random_state=RANDOM_SEED,
        n_jobs=-1
    )

    rf_model.fit(X_train, y_train)
    y_val_pred = rf_model.predict(X_val)

    print(f"\nClass weight {{-1:1, 1:{w}}}")
    print("Accuracy:", accuracy_score(y_val, y_val_pred))
    print("Precision:", precision_score(y_val, y_val_pred, pos_label=1, zero_division=0))
    print("Recall:", recall_score(y_val, y_val_pred, pos_label=1, zero_division=0))
    print("F1-score:", f1_score(y_val, y_val_pred, pos_label=1, zero_division=0))
    print("Confusion Matrix:\n", confusion_matrix(y_val, y_val_pred))


Class weight {-1:1, 1:3}
Accuracy: 0.9361702127659575
Precision: 0.0
Recall: 0.0
F1-score: 0.0
Confusion Matrix:
 [[220   0]
 [ 15   0]]

Class weight {-1:1, 1:5}
Accuracy: 0.9361702127659575
Precision: 0.0
Recall: 0.0
F1-score: 0.0
Confusion Matrix:
 [[220   0]
 [ 15   0]]

Class weight {-1:1, 1:10}
Accuracy: 0.9361702127659575
Precision: 0.0
Recall: 0.0
F1-score: 0.0
Confusion Matrix:
 [[220   0]
 [ 15   0]]

Class weight {-1:1, 1:15}
Accuracy: 0.9361702127659575
Precision: 0.0
Recall: 0.0
F1-score: 0.0
Confusion Matrix:
 [[220   0]
 [ 15   0]]


In [14]:
for n_estimators in [100, 200, 400]:
    for max_depth in [5, 10, None]:
        rf_model = RandomForestClassifier(
            n_estimators=n_estimators,
            max_depth=max_depth,
            class_weight="balanced",
            random_state=RANDOM_SEED,
            n_jobs=-1
        )

        rf_model.fit(X_train, y_train)
        y_val_pred = rf_model.predict(X_val)

        print(f"\nRandom Forest, n_estimators={n_estimators}, max_depth={max_depth}")
        print("Accuracy:", accuracy_score(y_val, y_val_pred))
        print("Precision:", precision_score(y_val, y_val_pred, pos_label=1, zero_division=0))
        print("Recall:", recall_score(y_val, y_val_pred, pos_label=1, zero_division=0))
        print("F1-score:", f1_score(y_val, y_val_pred, pos_label=1, zero_division=0))
        print("Confusion Matrix:\n", confusion_matrix(y_val, y_val_pred))


Random Forest, n_estimators=100, max_depth=5
Accuracy: 0.9361702127659575
Precision: 0.0
Recall: 0.0
F1-score: 0.0
Confusion Matrix:
 [[220   0]
 [ 15   0]]

Random Forest, n_estimators=100, max_depth=10
Accuracy: 0.9361702127659575
Precision: 0.0
Recall: 0.0
F1-score: 0.0
Confusion Matrix:
 [[220   0]
 [ 15   0]]

Random Forest, n_estimators=100, max_depth=None
Accuracy: 0.9361702127659575
Precision: 0.0
Recall: 0.0
F1-score: 0.0
Confusion Matrix:
 [[220   0]
 [ 15   0]]

Random Forest, n_estimators=200, max_depth=5
Accuracy: 0.9361702127659575
Precision: 0.0
Recall: 0.0
F1-score: 0.0
Confusion Matrix:
 [[220   0]
 [ 15   0]]

Random Forest, n_estimators=200, max_depth=10
Accuracy: 0.9361702127659575
Precision: 0.0
Recall: 0.0
F1-score: 0.0
Confusion Matrix:
 [[220   0]
 [ 15   0]]

Random Forest, n_estimators=200, max_depth=None
Accuracy: 0.9361702127659575
Precision: 0.0
Recall: 0.0
F1-score: 0.0
Confusion Matrix:
 [[220   0]
 [ 15   0]]

Random Forest, n_estimators=400, max_depth=

In [15]:
for min_samples_leaf in [1, 2, 4]:
    for min_samples_split in [2, 5, 10]:
        rf_model = RandomForestClassifier(
            n_estimators=200,
            max_depth=10,
            min_samples_leaf=min_samples_leaf,
            min_samples_split=min_samples_split,
            class_weight="balanced",
            random_state=RANDOM_SEED,
            n_jobs=-1
        )

        rf_model.fit(X_train, y_train)
        y_val_pred = rf_model.predict(X_val)

        print(f"\nRandom Forest, min_samples_leaf={min_samples_leaf}, min_samples_split={min_samples_split}")
        print("Accuracy:", accuracy_score(y_val, y_val_pred))
        print("Precision:", precision_score(y_val, y_val_pred, pos_label=1, zero_division=0))
        print("Recall:", recall_score(y_val, y_val_pred, pos_label=1, zero_division=0))
        print("F1-score:", f1_score(y_val, y_val_pred, pos_label=1, zero_division=0))
        print("Confusion Matrix:\n", confusion_matrix(y_val, y_val_pred))


Random Forest, min_samples_leaf=1, min_samples_split=2
Accuracy: 0.9361702127659575
Precision: 0.0
Recall: 0.0
F1-score: 0.0
Confusion Matrix:
 [[220   0]
 [ 15   0]]

Random Forest, min_samples_leaf=1, min_samples_split=5
Accuracy: 0.9361702127659575
Precision: 0.0
Recall: 0.0
F1-score: 0.0
Confusion Matrix:
 [[220   0]
 [ 15   0]]

Random Forest, min_samples_leaf=1, min_samples_split=10
Accuracy: 0.9361702127659575
Precision: 0.0
Recall: 0.0
F1-score: 0.0
Confusion Matrix:
 [[220   0]
 [ 15   0]]

Random Forest, min_samples_leaf=2, min_samples_split=2
Accuracy: 0.9361702127659575
Precision: 0.0
Recall: 0.0
F1-score: 0.0
Confusion Matrix:
 [[220   0]
 [ 15   0]]

Random Forest, min_samples_leaf=2, min_samples_split=5
Accuracy: 0.9361702127659575
Precision: 0.0
Recall: 0.0
F1-score: 0.0
Confusion Matrix:
 [[220   0]
 [ 15   0]]

Random Forest, min_samples_leaf=2, min_samples_split=10
Accuracy: 0.9361702127659575
Precision: 0.0
Recall: 0.0
F1-score: 0.0
Confusion Matrix:
 [[220   0]
 [

In [16]:
best_rf = RandomForestClassifier(
    n_estimators=200,
    max_depth=10,
    min_samples_leaf=1,
    min_samples_split=2,
    class_weight="balanced",
    random_state=RANDOM_SEED,
    n_jobs=-1
)

best_rf.fit(X_train, y_train)
y_test_pred = best_rf.predict(X_test)

print("Test Accuracy:", accuracy_score(y_test, y_test_pred))
print("Test Precision:", precision_score(y_test, y_test_pred, pos_label=1, zero_division=0))
print("Test Recall:", recall_score(y_test, y_test_pred, pos_label=1, zero_division=0))
print("Test F1-score:", f1_score(y_test, y_test_pred, pos_label=1, zero_division=0))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_test_pred))

Test Accuracy: 0.9279661016949152
Test Precision: 0.0
Test Recall: 0.0
Test F1-score: 0.0
Confusion Matrix:
 [[219   1]
 [ 16   0]]


In [ ]:

feature_names = [f"feat_{i}" for i in range(X_train.shape[1])]
X_train = np.asarray(preprocessed_data["X_train"], dtype=np.float64)

feature_importance = pd.DataFrame({
    "feature": feature_names,
    "importance": best_rf.feature_importances_
})